### ISSUE TITLE
fails on Racket CS

### ISSUE THREAD

**Issue by samth** [wargrey/graphics#3]
This package fails to build (and causes the `raco setup` process to get corrupted) on Racket CS. You can see the failure here: https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/graphics.txt

The error there is use of `make-sized-byte-string`, which is not supported on Racket CS.

**Comment by samth** [comment]
You can see some porting information here: https://github.com/racket/racket/blob/master/racket/src/cs/README.txt#L347

**Comment by wargrey** [comment]
> You can see some porting information here: https://github.com/racket/racket/blob/master/racket/src/cs/README.txt#L347

**Comment by wargrey** [comment]
@samth hi, thank you to mention me that info.

But I didn't use `make-sized-byte-string` in this package.
It appeared in the (non-public) dependent package, and that code has never been actually used.
So I removed it completely, and let's see if the issue is solved.

**Comment by samth** [comment]
I just tried installing `graphics` and I continue to see errors.

**Comment by samth** [comment]
The relevant code is here: https://github.com/wargrey/graphics/blob/master/bitmap/digitama/unsafe/convert.rkt#L49; I think to fix it you'd just need to copy the data.

**Comment by wargrey** [comment]
@samth I am sorry I forgot that since it has been a long time not using FFI and C-level APIs. Now it should work.

These days I have been writing my own zip/unzip in Typed Racket, after that I will completely replace the low level code for converting bitmap to png.
